/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package be.esi.alg2.arbre.gui;

import be.esi.alg2.arbre.db.ArbreDB;
import be.esi.alg2.arbre.db.ArbreDbException;
import be.esi.alg2.arbre.dto.ArbreCompletDto;
import be.esi.alg2.arbre.dto.ArbreDto;
import be.esi.alg2.arbre.metier.ArbreBinaireFacade;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author florian
 */
public class ChargerArbreJDialog extends javax.swing.JDialog {
    
    public static final String chargementArbre = "chargementArbre";
    private ArbreCompletDto arbreACharger;
    
    /**
     * Creates new form ChargerArbreJDialog
     */
    public ChargerArbreJDialog(java.awt.Frame parent, boolean modal) throws ArbreDbException {
        super(parent, modal);
        initComponents();
        this.setTitle("Recherche d'un arbre à charger");
        chargerArbre("");
        arbreACharger = null;
    }
    
    public ArbreCompletDto getArbreACharger(){
        return arbreACharger;
    }
    
    private void chargerArbre(String nom) throws ArbreDbException{
        arbreJList.setListData(ArbreDB.listeNoms(nom).toArray());
        arbreJList.revalidate();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        arbreJList = new javax.swing.JList();
        nomArbreJTF = new javax.swing.JTextField();
        chargerJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jScrollPane1.setViewportView(arbreJList);

        nomArbreJTF.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                nomArbreJTFCaretUpdate(evt);
            }
        });

        chargerJButton.setText("Charger");
        chargerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chargerJButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Rechercher:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(chargerJButton))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(nomArbreJTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 238, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(nomArbreJTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 164, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(chargerJButton)
                .add(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chargerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chargerJButtonActionPerformed
        if(arbreJList.getSelectedValue() != null){
            ArbreDto unArbre = (ArbreDto) arbreJList.getSelectedValue();
            arbreACharger = ArbreBinaireFacade.chargeArbre(unArbre.getId());
            firePropertyChange(chargementArbre, null, arbreACharger);
            this.setVisible(false);
        }
    }//GEN-LAST:event_chargerJButtonActionPerformed

    private void nomArbreJTFCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_nomArbreJTFCaretUpdate
        try {
            chargerArbre(nomArbreJTF.getText());
        } catch (ArbreDbException ex) {
            Logger.getLogger(ChargerArbreJDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_nomArbreJTFCaretUpdate

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList arbreJList;
    private javax.swing.JButton chargerJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomArbreJTF;
    // End of variables declaration//GEN-END:variables
}
